name: Fetch Zenn Articles

on:
  schedule:
    - cron: '0 0 * * *'  # UTCで0時 → 日本時間で9時ごろ
  workflow_dispatch: 

jobs:
  fetch_zenn:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install feedparser
        run: pip install feedparser requests

      - name: Fetch Zenn RSS and Post
        working-directory: ./backend
        env:
          API_URL: http://localhost:8080/zenn_articles  # ECSデプロイ後に本番用URLに変更する
          ZENN_FEED_URL: https://zenn.dev/k__kanke/feed
        run: |
          python scripts/fetch_zenn.py
